# =======================================================
# Configuration for "Meta-learning of quantum systems"
# =======================================================

experiment:
  # Choose the problem and model for the experiment.
  # problem_type: 'MaxCut', 'SK', 'TFIM1D', 'TFIM2D'
  problem_type: 'MaxCut'
  # model_type: 'RBM', 'CNN'
  model_type: 'CNN'
  # Task diversity parameter (variance is sigma^2)
  sigma: 0.5 # Paper tests 0.2, 0.5, 1.0

problem_params:
  # Common parameters
  num_spins: 49 # For 2D, this should be L*L. Here 7x7=49. For 1D, L=49.
  
  # TFIM specific base transverse field
  transverse_field: 1.0 # The base 'h' field strength

model_params:
  # RBM specific: alpha = num_hidden / num_visible
  rbm_alpha: 0.5
  # CNN specific
  cnn_depth: 128 # Number of channels in the conv layer

vmc:
  # Batch size for MCMC sampling
  n_samples: 1024 # Paper: inner loop batch size 1024

maml:
  # Outer loop settings
  meta_epochs: 50
  meta_lr: 0.002
  meta_batch_size: 16
  # Inner loop settings
  inner_steps: 1
  inner_lr: 0.005

evaluation:
  num_test_tasks: 8
  finetune_steps: 300